apiVersion: v1
kind: Service

metadata:
    labels:
        app: prometheus
    name: prometheus-svc

spec:
    clusterIP: None
    ports:
        - port: 9090
    selector:
        app: prometheus

---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: prometheus-deployment
    namespace: monitoring
    labels:
        app: prometheus

spec:
    replicas: 1
    selector:
        matchLabels:
            app: prometheus

    template:
        metadata:
            labels:
                app: prometheus

        spec:
            containers:
                - name: prometheus
                  image: prom/prometheus:v2.43.0
                  args:
                      - '--storage.tsdb.retention.time=12h'
                      - '--config.file=/etc/prometheus/prometheus.yml'
                      - '--storage.tsdb.path=/prometheus/'
                  ports:
                      - containerPort: 9090

                  resources:
                      requests:
                          cpu: '0.5'
                          memory: '2G'
                      limits:
                          cpu: '0.5'
                          memory: '2G'

                  volumeMounts:
                      - name: prometheus-config-volume
                        mountPath: /etc/prometheus/
                      - name: prometheus-vol
                        mountPath: /prometheus/

            volumes:
                - name: prometheus-config-volume
                  configMap:
                      defaultMode: 420
                      name: prometheus-server-conf
                - name: prometheus-vol
                  persistentVolumeClaim:
                      claimName: prometheus-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: prometheus-pvc
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: local-path
    resources:
        requests:
            storage: 4Gi
