apiVersion: v1
kind: ConfigMap

metadata:
    name: prometheus-server-conf
    labels:
        name: prometheus-server-conf
    namespace: monitoring

data:
    prometheus.rules: |-
        groups:
        - name: devopscube demo alert
          rules:
          - alert: High Pod Memory
            expr: sum(container_memory_usage_bytes) > 1
            for: 1m
            labels:
              severity: slack
            annotations:
              summary: High Memory Usage

    prometheus.yml: |-
        global:
          scrape_interval: 5s
          evaluation_interval: 5s

        rule_files:
          - /etc/prometheus/prometheus.rules

        alerting:
          alertmanagers:
          - scheme: http
            static_configs:
            - targets:
              - "alertmanager.monitoring.svc:9093"

        scrape_configs:
          - job_name: 'node-exporter'
            kubernetes_sd_configs:
              - role: endpoints
            relabel_configs:
            - source_labels: [__meta_kubernetes_endpoints_name]
              regex: 'node-exporter'
              action: keep

          - job_name: 'kubernetes-apiservers'
            kubernetes_sd_configs:
            - role: endpoints
            scheme: https
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            relabel_configs:
            - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
              action: keep
              regex: default;kubernetes;https

          - job_name: 'kubernetes-nodes'
            scheme: https
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            kubernetes_sd_configs:
            - role: node
            relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/${1}/proxy/metrics

          - job_name: 'kubernetes-pods'
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
              action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: kubernetes_namespace
            - source_labels: [__meta_kubernetes_pod_name]
              action: replace
              target_label: kubernetes_pod_name

          - job_name: 'kube-state-metrics'
            static_configs:
              - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

          - job_name: 'kubernetes-cadvisor'
            scheme: https
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            kubernetes_sd_configs:
            - role: node
            relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

          - job_name: 'kubernetes-service-endpoints'
            kubernetes_sd_configs:
            - role: endpoints
            relabel_configs:
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
              action: replace
              target_label: __scheme__
              regex: (https?)
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
              action: replace
              target_label: __address__
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: kubernetes_namespace
            - source_labels: [__meta_kubernetes_service_name]
              action: replace
              target_label: kubernetes_name

          # - job_name: 'strimzi'
          #   static_configs:
          #     - targets: ['my-cluster-kafka-brokers.strimzi-system.svc.cluster.local:9404']

          # - job_name: 'cassandra'
          #   static_configs:
          #     - targets: ['cassandra-metrics.cassandra.svc.cluster.local:7070']

          - job_name: 'cassandra'
            honor_labels: true
            metrics_path: /metrics
            kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                    - cassandra
            relabel_configs:
              - source_labels: [__meta_kubernetes_endpoint_port_name]
                regex: 'cassandra-metrics'
                action: keep
                replacement: '${1}'
              # - source_labels: [__address__]
              #   target_label: instance
              #   regex: "(.*):.*"
              #   replacement: "$1:7070"

          - job_name: 'pushgateway'
            honor_labels: true
            static_configs:
              - targets: ['pushgateway-svc.monitoring.svc.cluster.local:9091']

          - job_name: 'strimzi'
            scrape_interval: 15s
            honor_labels: true
            metrics_path: /metrics
            kubernetes_sd_configs:
              - role: pod
                namespaces:
                  names:
                    - strimzi-system
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_name]
                regex: 'my-cluster-kafka-exporter.*'
                action: keep

          # - job_name: 'strimzi'
          #   kubernetes_sd_configs:
          #   - role: pod
          #     namespaces:
          #       names:
          #         - strimzi-system
          #   relabel_configs:
          #   - source_labels: [__meta_kubernetes_pod_label_app]
          #     action: keep
          #     regex: exporter
          #   - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          #     action: replace
          #     target_label: _address_
          #     regex: (.+):(\d+)
          #     replacement: $1

          # - job_name: 'importer'
          #   static_configs:
          #     - targets: ['importer-svc.zenprice.svc.cluster.local:9091']
          
          # - job_name: 'predicter'
          #   static_configs:
          #     - targets: ['predicter-svc.zenprice.svc.cluster.local:9091']
