apiVersion: v1
kind: Service

metadata:
    labels:
        app: pushgateway
    name: pushgateway-svc

spec:
    clusterIP: None
    ports:
        - port: 9091
    selector:
        app: pushgateway

---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: pushgateway-deployment
    namespace: monitoring
    labels:
        app: pushgateway

spec:
    replicas: 1
    selector:
        matchLabels:
            app: pushgateway

    template:
        metadata:
            labels:
                app: pushgateway

        spec:
            containers:
                - name: pushgateway
                  image: prom/pushgateway:v1.5.1
                  ports:
                      - containerPort: 9091
                  resources:
                      requests:
                          cpu: '0.5'
                          memory: '512M'
                      limits:
                          cpu: '0.5'
                          memory: '512M'

                  volumeMounts:
                      - name: pushgateway-vol
                        mountPath: /prometheus/

            volumes:
                - name: pushgateway-vol
                  persistentVolumeClaim:
                      claimName: pushgateway-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pushgateway-pvc
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: local-path
    resources:
        requests:
            storage: 1Gi
