apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: predicter

spec:
  # serviceName: predicter-svc
  replicas: 1
  selector:
    matchLabels:
      app: predicter

  template:
    metadata:
      labels:
        app: predicter

    spec:
      containers:
      - name: spark-py
        image: d1scak3/predicter:1.0
        env:
          - name: CASSANDRA_USER
            value: "cassandra"
          - name: CASSANDRA_PASSWORD
            value: "cassandra"
          - name: CASSANDRA_KEYSPACE
            value: "zenprice"
          - name: CASSANDRA_SRC_TABLE
            value: "postgres_values"
          - name: CASSANDRA_DST_TABLE
            value: "predicted_values"
          - name: PRODUCT_MODEL
            value: "samsung Galaxy A51 128GB"
          - name: PRODUCT_ID
            value: 83
          - name: PRODUCT_SUB
            value: "unlocked"
          - name: COMPANY
            value: "Abcdin"
          - name: COUNTRY
            value: "CL"
