# core components
input:
    label: 'psql'
    sql_raw:
        driver: 'postgres'
        dsn: 'postgres://postgres:mysecretpassword@localhost:5432/zenprice?sslmode=disable'
        query:
            'select rim_facts.id, prices.id, plans.id, prices.created_at, prices.updated_at, prices.value, prices.currency, plans.plan_type
            from rim_facts, prices, plans
            where rim_facts.plan_id = plans.id
            and rim_facts.price_id = prices.id'
        args_mapping: 'root = []'

buffer:

pipeline:

output:
