apiVersion: v1
kind: Service

metadata:
    labels:
        app: graphql
    name: graphql-svc

spec:
    clusterIP: None
    ports:
        - port: 8080
    selector:
        app: graphql

---
apiVersion: v1
kind: Service

metadata:
    name: graphql-lb-svc
    labels:
        app: graphql

spec:
    selector:
        app: graphql
    ports:
        - port: 8080
          targetPort: 8080
    type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: graphql-deployment
    labels:
        app: graphql

spec:
    selector:
        matchLabels:
            app: graphql

    template:
        metadata:
            labels:
                app: graphql

        spec:
            containers:
                - name: graphql
                  image: stargateio/graphqlapi:v2
                  ports:
                      - containerPort: 8080
                  resources:
                      limits:
                          cpu: '0.5'
                          memory: 1G
                      requests:
                          cpu: '0.5'
                          memory: 1G
                  env:
                      - name: QUARKUS_GRPC_CLIENTS_BRIDGE_HOST
                        value: 'coordinator-svc.cassandra.svc.cluster.local'
                      - name: QUARKUS_GRPC_CLIENTS_BRIDGE_PORT
                        value: '8091'
                      - name: QUARKUS_HTTP_ACCESS_LOG_ENABLED
                        value: 'true'
                      - name: QUARKUS_LOG_LEVEL
                        value: 'INFO'
