FROM apache/spark-py:3.3.1

ENV SPARK_MASTER_HOST=spark-master
ENV SPARK_MASTER_PORT=7077
ENV SPARK_MASTER_WEBUI_PORT=8080
ENV SPARK_NO_DAEMONIZE=true

# ENV SPARK_LOG_DIR=/opt/spark/logs
# ENV SPARK_MASTER_LOG=/opt/spark/logs/spark-master.out

# USER root

# RUN mkdir -p $SPARK_LOG_DIR && \
# touch $SPARK_MASTER_LOG && \
# ln -sf /dev/stdout $SPARK_MASTER_LOG
# RUN chown 185 ${SPARK_MASTER_LOG} && \
# chmod 666 ${SPARK_MASTER_LOG}

# USER 185

CMD [ "/opt/spark/sbin/start-master.sh" ]